### PR TITLE
Enable lepton and trigger filters

### PR DESCRIPTION
**Pull request by dantrim**
- Using the trigger histogram to check if integral is > 0
to check that a trigger has fired

Before pushing to xaod, just want to make sure everyone agrees with the method for the filters.

### CODE REVIEW

**Comment by ataffard** [comment]
Let me make sure I understand. 
The histogram will get fill with only a specific list of triggers. So if we were to store few more triggers as backup, then this would select the event as well. We can test like this and see if we need to do something more fancy as primary & secondary trigger lists.

For the number of lepton, we need also something for tau. The 3lep has 1e/u + 2 hadTau selection.
Don't we want to do the lepton filtering on the baseline lepton , ie a la run-1 ?

**Comment by gerbaudo** [comment]
The run 1 implementation would count the number of leptons
that will be stored in the output nutple, and make the decision
based on that
```
uint nLepSaved = m_susyNt.ele()->size() + m_susyNt.muo()->size();
```
see for example 
https://github.com/gerbaudo/SusyCommon/blob/42230d5ba04b71dc0eb309ce38b23a4bcac3a34f/Root/SusyNtMaker.cxx#L454

I think that was a sensible choice: independently of what we
decide to store (pre, baseline, signal), we store only events
that have at least N leptons of that type.
I would suggest that you count on `m_susyNt.ele()` and `m_susyNt.muo()`.
We can worry about taus in the next iteration.

**Comment by dantrim** [comment]
@ataffard The histogram will bin all triggers in the set requested by the analysis/user, so if none of them fire then don't we want to skip the event (i.e. Is this the logic)? So I am not sure what you mean by back up triggers - if we break up the triggers by analysis to skim, then presumably we would be including the relevant backups, no? Otherwise we just don't break up the lists and include all analyses' triggers in the ntuple. This is what is done in the run1 SusyNtMaker I think.

@gerbaudo at this point in SusyNtMaker the SusyNtObject is not yet filled for the current event, right? So I didn't think we could implement it this way. As we store the pre-leptons, is checking their size here effectively the same as in the run1 SusyNtMaker?

**Comment by gerbaudo** [comment]
The `SusyNt` object in memory should already have all the vector filled,
even though the event hasn't been saved in the tree yet.
```
if(selectEvent() && m_fillNt){
  m_outTree->Fill();
...
}
```
Regarding the triggers: I like your implementation. If we want to store a few
trigger bits in addition to the ones that are used to filter the events, we can
just
- fill the trigger histogram with `XaodAnalysis::xaodTriggers() + XaodAnalysis::xaodAdditionalTriggers()`
- count the trigger using only the bins `XaodAnalysis::xaodTriggers()`
It will require very little change. I think this implementation is good enough for `n0205`.

**Comment by gerbaudo** [comment]
After looking at the code more carefully: @dantrim you're right, the output is not filled yet.
So for this production the event selection is good as it is now.
It will be improved when we implement gerbaudo/SusyCommon#60
Merging and closing.

**Pull request merged**
